name-template: 'v$RESOLVED_VERSION 🚀'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'type:feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'type:bug'
  - title: '📚 Documentation'
    labels:
      - 'type:docs'
  - title: '� Research'
    labels:
      - 'type:research'
  - title: '🔧 Maintenance'
    labels:
      - 'type:chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'type:feature'
  patch:
    labels:
      - 'type:bug'
      - 'type:docs'
      - 'type:chore'
  default: patch
template: |
  ## Changes

  $CHANGES
